### ISSUE TITLE
JupyterView Roadpath

### ISSUE THREAD

**Issue by bjlittle** [trungleduc/jupyterview#35]
@trungleduc Thanks for `jupyterview`, it's pretty darn awesome 😍 

Just thought I'd share with you `jupyterview` visualising some [AWI-CM FESOM](https://fesom.de/cmip6/work-with-awi-cm-unstructured-data/) climate data, where each `vtk` mesh consists of 126,859 cells and 2,283,462 points 👍 

Also, I have a couple of questions:

1. I was just wondering what the roadpath is for `jupyterview`? Do you have any plans that you're able to share?
1. Are there plans to extend `jupyterview` to allow more than one VTK object to be added to the scene? Or, if that's already possible, how do you do it? 
1. Is it easy for you to share instructions on how to publish `jupyterview` and run with [jupyterlite](https://github.com/jupyterlite/jupyterlite)?

Ping @koldunovn (yeah, I know it's not the triangulated version of the mesh, but still very cool!)

https://user-images.githubusercontent.com/2051656/168305776-cb6b389b-c375-412b-b516-6f96c3ea04c8.mp4

**Comment by bjlittle** [comment]
@trungleduc Fancy enabling GH Discussions for your repo?

**Comment by trungleduc** [comment]
Hi @bjlittle, thank you for sharing your use case. It looks awesome!

> 
> 1. I was just wondering what the roadpath is for `jupyterview`? Do you have any plans that you're able to share?

- I'm working in #34 to support more file types  by using the [`meshio`](https://github.com/nschloe/meshio) package. With this update, `jupyterview` can read a lot more mesh file type, for example : Abaqus (.inp), ANSYS msh (.msh),  CGNS (.cgns), DOLFIN XML (.xml)...
I would love to hear about your suggestions to improve `jupyterview`. 

> 2. Are there plans to extend `jupyterview` to allow more than one VTK object to be added to the scene? Or, if that's already possible, how do you do it?

- Technically it's possible, but since I started `jupyterview` as a single document viewer, it needs a lot of changes in the UI.

> 3. Is it easy for you to share instructions on how to publish `jupyterview` and run with [jupyterlite](https://github.com/jupyterlite/jupyterlite)?
> 
- You can take a look at https://github.com/trungleduc/jupyterview/blob/master/.github/workflows/deploy.yml .  I used this workflow to deploy `jupyterview` with `jupyterlite` to Github page.

**Comment by bjlittle** [comment]
@trungleduc As suggestions for improvements, having a "follow-mode" to focus and zoom the camera through a scene would be fantastic e.g., by double clicking to fly to the location of the mouse in the scene. For example, exploring this relatively complex river basin with tributaries is possible with `jupyterview`, but a little difficult:

https://user-images.githubusercontent.com/2051656/168390294-1f2cec27-4947-4ebb-b32c-7837bc64a55c.mp4

This is the same scene, but using [pyvista](https://github.com/pyvista/pyvista) with focus and zoom to make the interaction more natural and intuitive:

https://user-images.githubusercontent.com/2051656/168390777-e9897289-ff61-4ef1-8e52-92c80a6c397d.mp4

**Comment by bjlittle** [comment]
@trungleduc If you could offer more colormaps out-the-box, such as the perceptually accurate colormaps from [colorcet](https://colorcet.holoviz.org/) or indeed [cmocean](https://matplotlib.org/cmocean/), then that would be marvellous and make a huge difference.

For example, it would really enhance visualizations of salinity changing with the tide:

https://user-images.githubusercontent.com/2051656/168392784-8e8fcd3f-dedb-48b2-8a1d-d0862e55b1bf.mp4

Awesome, thanks! 👍

**Comment by bjlittle** [comment]
> * You can take a look at https://github.com/trungleduc/jupyterview/blob/master/.github/workflows/deploy.yml .  I used this workflow to deploy `jupyterview` with `jupyterlite` to Github page.

Brilliant, thanks... I take a look at that 👍

**Comment by bjlittle** [comment]
Also, being able to simply change the background colour and add a title to the scene would be useful 👍

**Comment by bjlittle** [comment]
@trungleduc Did you have a specific use case for adding the warping to the UI?

Personally, I'd tend to pre-warp and save the mesh rather than do it interactively. Also, warping by a fixed normal is limiting, but being able to compute the normals of the faces (and flip) and then warp by those could potentially be more useful... but I guess it depends on what the user is trying to achieve.

**Comment by bjlittle** [comment]
@trungleduc Just to clarify, for the `pvd` file format, is the `timestep` the intended delay between rendered frames?

i.e., so here it's `100ms`, right? (given that each frame in reality can be rendered that quickly)
```
<?xml version="1.0"?>
<VTKFile type="Collection" version="0.1">
    <Collection>
        <DataSet timestep="0.000000E+00" file="tamar_salinity_000.vtk"/>
        <DataSet timestep="0.100000E+00" file="tamar_salinity_001.vtk"/>
        <DataSet timestep="0.200000E+00" file="tamar_salinity_002.vtk"/>
        <DataSet timestep="0.300000E+00" file="tamar_salinity_003.vtk"/>
    </Collection>
</VTKFile>
```

**Comment by koldunovn** [comment]
@bjlittle just to say the AWI-CM example (as well as others :)) looks great! :)

**Comment by trungleduc** [comment]
Sorry for my late reply

> Also, some minor requests:
> 
> * being able to simply change the background colour

> * add a title to the scene
> * control the title of the colorbar/scalarbar (rather than default to the name of the scalar)
> * the `Color by` drop-down also indicates for each scalar it's location i.e., `points` or `cells`, which will help differentiate to the user between two scalar arrays attached to the mesh with the **same** name but on **different** mesh locations.
> 
> Would all be really useful 😃

Thank you for your very helpful suggestions. I created the 0.5.0 release plan #36. It would be great if you could put your suggestion into independent issues, I will tag them with the 0.5.0 milestone

**Comment by trungleduc** [comment]
> @trungleduc Did you have a specific use case for adding the warping to the UI?
> 
> Personally, I'd tend to pre-warp and save the mesh rather than do it interactively.
> 
> That said, warping by a fixed normal is limiting, but `jupyterview` being able to compute the normals of the points/faces (and option to flip them) and then warp by those could potentially be more useful?... but I guess it depends on what the user is trying to achieve.
> 
> Anyways, if you supported this then I could easily load the flattened bathymetry mesh and warp the points by scalar depth to dynamically create the scene shown above. That would help to easily determine the warp factor that suits the users needs... now that would be pretty cool 😉
> 
> Or are you assuming/preferring that the user pre-computes and attaches the normals to the mesh? If so, then being able to select the existing normals on the mesh from the UI and warp by those might be an easier option to support from the perspective of `jupyterview`

From my experience in solid mechanics, we want to plot different stress fields on a deformed mesh, so having interactive wrapping is quite useful.
What I want to do is a "wrap by vector", just like in ParaView but this feature is not available yet on `vtk.js`, the base library that i used in `jupyterview`

**Comment by trungleduc** [comment]
> @trungleduc Just to clarify, for the `pvd` XML file format, is the `timestep` the intended delay between rendered frames?
> 
> i.e., so here it's `100ms`, right? (given that each frame in reality can be rendered that quickly)
> 
> ```
> <?xml version="1.0"?>
> <VTKFile type="Collection" version="0.1">
>     <Collection>
>         <DataSet timestep="0.000000E+00" file="tamar_salinity_000.vtk"/>
>         <DataSet timestep="0.100000E+00" file="tamar_salinity_001.vtk"/>
>         <DataSet timestep="0.200000E+00" file="tamar_salinity_002.vtk"/>
>         <DataSet timestep="0.300000E+00" file="tamar_salinity_003.vtk"/>
>     </Collection>
> </VTKFile>
> ```
> 
> Also, is there a limit to the number of frames that can be in a collection? i.e., do you load all the frame meshes into memory before rendering or do you have a lazy loading/render scheme?

I fixed the framerate at 24fps, the `timestep` is used just for labeling the frame. And yes, all the meshes are loaded into memory before rendering, and the frames are cached so I only need to render once for each mesh.
