### ISSUE TITLE
Read mesh files

### ISSUE THREAD

**Issue by hbadi** [trungleduc/jupyterview#38]
Hi,

I just discovered your amazing extensions and installed it with ananonda/python39/win. I can read vtu/vtk files but when it comes to others mesh files (gmsh msh or mesh Medit files) the viewer enter an infinite loop. Jupyterview relies on meshio to read various mesh files, i can manually use meshio. What's wrong ?

Best regards.

**Comment by trungleduc** [comment]
Hello, thank you for your feedback, can you provide me your mesh file?

**Comment by hbadi** [comment]
Here the mesh&msh files.
[mesh.zip](https://github.com/trungleduc/jupyterview/files/8943831/mesh.zip)

**Comment by trungleduc** [comment]
Thanks, i will take a look at it.

**Comment by trungleduc** [comment]
Hey @hbadi, I released `0.5.1`, it should fix your issue. You can install the newest version with `pip install jupyterview==0.5.1`

https://user-images.githubusercontent.com/4451292/175162333-82a8e987-3668-4fb7-9532-d9ecf9d493c3.mp4

**Comment by hbadi** [comment]
Hi,
Great ! I can't install it on conda-forge (0.5.1 is not yet available).

**Comment by trungleduc** [comment]
Now it is

**Comment by hbadi** [comment]
I just update to 0.5.1 and still not working...

**Comment by trungleduc** [comment]
> I just update to 0.5.1 and still not working...

maybe it's something related to Windows, but I don't have any Windows machine to try out.

**Comment by hbadi** [comment]
Ok, thanks !

**Comment by trungleduc** [comment]
`0.5.2` is out on pypi with the Windows patch, for conda you need to wait for tomorrow

**Comment by hbadi** [comment]
I got it, thanks !
